### ISSUE TITLE
offline attacks work

### ISSUE THREAD

**Issue by OmniNisis** [CrimsonMods/OfflineRaidGuard#7]
Palisades take damage while the player is offline. Only furniture does not take damage when the player is offline, before and after the intrusion.

What's the solution?  
Thanks

**Comment by SkyTech6** [comment]
OfflineRaidGuard will soon be deprecated. The functionality will be improved and refactored in an upcoming CrimsonRaidGuard mod.

**Comment by OmniNisis** [comment]
OK, when is this planned?
